[project]
name = "draftly"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "Django==6.1",
    "dj-database-url==3.1.2",
    "psycopg[binary]==3.3.4",
    "whitenoise==6.12.0",
]

[tool.vercel.scripts]
build = 'python manage.py collectstatic --noinput && if [ -n "$DATABASE_URL" ]; then python manage.py migrate --noinput; fi'
