databases:
  - name: draftly-db
    plan: free
services:
  - type: web
    name: draftly
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn collabdocs.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: draftly-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://draftly.onrender.com
